### ISSUE TITLE
Small typo / Other Suggestion

### ISSUE THREAD

**Issue by ghost** [yiselieren/ReLaunch#2]
Very nice program!

There is a typo in the settings ("Seacrh settings").

Is there any way to add a setting to close the favorites/recent/app drawer when an item is launched?

**Comment by yiselieren** [comment]
Thank you,

I fixed the typo, but I still don't understand what you mean by "item is launched". Do you mean some reader called for some file? In such case it up to reader to refresh the screen. Can you please explain your feature request in more details?

**Comment by ghost** [comment]
I was thinking that when you load an application from the App Drawer or
from the favorites list, it could (optionally) close the drawer/list and go
back to the main screen.

On Fri, Nov 25, 2011 at 4:01 PM, yiselieren <
reply@reply.github.com

**Comment by yiselieren** [comment]
OK, now its clear. Its pretty easy to do that by adding some special property. Added to TODO list.

**Comment by yiselieren** [comment]
Done since 1.2.5
