### ISSUE TITLE
Can you make a version for Sony PRS-T1?

### ISSUE THREAD

**Issue by aeacan** [yiselieren/ReLaunch#6]
Thanks for your job.
   I run it on my PRS-T1.It;s great,but some places are not suitable for T1.The biggest problem is it is not suitable for the lcd density of the T1,some information can not be fully displayed.The lcd density of Nook is 167,T1 is 240.

**Comment by avmdv** [comment]
More details please, that it is not fully displayed? The fact that in one and the other device uses the same display E Ink Pearl.

**Comment by aeacan** [comment]
Bottom of the screen,time, memory, wifi and battery information can not be fully displayed, can be resolved by modifying the lcd density, but then the notification bar does not display properly.

**Comment by avmdv** [comment]
I tried to run ReLaunch on the emulator with a lcd density of 240dpi. You're right, it looks awful.
Your issue is accepted, but implementation will take some time.

**Comment by aeacan** [comment]
Thank you, I am very much looking forward to the new version.

**Comment by avmdv** [comment]
Fixed in version 1.3.3
